/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nqueens;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testNumberOfPositionsForFindAll() {
        // tests for find all
        NQueensBacktrack nq = new NQueensBacktrack(4);
        assertEquals(nq.computePositions(true), 2);

        nq = new NQueensBacktrack(5);
        assertEquals(nq.computePositions(true), 0);

        nq = new NQueensBacktrack(6);
        assertEquals(nq.computePositions(true), 0);

        nq = new NQueensBacktrack(7);
        assertEquals(nq.computePositions(true), 0);

        nq = new NQueensBacktrack(8);
        assertEquals(nq.computePositions(true), 8);

        nq = new NQueensBacktrack(10);
        assertEquals(nq.computePositions(true), 40);
    }

    @Test
    public void testNumberOfPositionsForFindOne() {
        // tests for find one
        NQueensBacktrack nq = new NQueensBacktrack(4);
        assertEquals(nq.computePositions(false), 1);

        nq = new NQueensBacktrack(5);
        assertEquals(nq.computePositions(false), 0);

        nq = new NQueensBacktrack(6);
        assertEquals(nq.computePositions(false), 0);

        nq = new NQueensBacktrack(7);
        assertEquals(nq.computePositions(false), 0);

        nq = new NQueensBacktrack(8);
        assertEquals(nq.computePositions(false), 1);

        nq = new NQueensBacktrack(10);
        assertEquals(nq.computePositions(false), 1);
    }

    @Test
    public void testSolutionsForMinConflict() {
        NQueensMinConflict nq = new NQueensMinConflict(4);
        assertTrue(nq.computePositions());

        nq = new NQueensMinConflict(5);
        assertFalse(nq.computePositions());

        nq = new NQueensMinConflict(6);
        assertFalse(nq.computePositions());

        nq = new NQueensMinConflict(7);
        assertFalse(nq.computePositions());

        nq = new NQueensMinConflict(8);
        assertTrue(nq.computePositions());

        nq = new NQueensMinConflict(10);
        assertTrue(nq.computePositions());

        nq = new NQueensMinConflict(100);
        assertTrue(nq.computePositions());
    }

}
